baseurl = "http://www.example.com"
title = "Cactus Factus"
​
theme = "coder"
​
languagecode = "en"
defaultcontentlanguage = "en"
​
paginate = 20
canonifyurls = true
​
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
​
disqusShortname = "yourdiscussshortname"
​
[params]
    author = "Cactus Factus"
    description = "Cactus Factus's website"
    keywords = "content, clients"
    info = "The spikiest content strategist"
    avatarurl = "img/cactus_factus.jpg"
    footercontent = "Copyright © 2019 Cactus Factus"
    font = "arial"
​
    dateformat = "January 2, 2006"
​
    hideCredits = false
    hideCopyright = false
​
    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"
​
    rtl = false
​
    
    colorscheme = "light"
    
​
​
​
#[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
​
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 3
    url = "https://instagram.com"
​
​
[languages]
    [languages.en]
        languagename = "English"
​
        [languages.en.menu]
​
            [[languages.en.menu.main]]
            name = "About"
            url = "/about/"
​
	    [[languages.en.menu.main]]
            name = "Clients"
            url = "/clients/"
​
            [[languages.en.menu.main]]
            name = "Contact"
            url = "/contact/"
